import Head from "next/head";
import NavBar from "../components/navbar/navbar";
import Header from "../components/header/header";
import Features from "../components/features/features";
import Documentation from "../components/documentation/documentation";
import Pricing from "../components/pricing/pricing";
import { Box } from "@chakra-ui/react";
import Footer from "../components/footer/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>yesNo API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box id="home"></Box>

      <NavBar />

      <Header />

      <Features />

      <Documentation />

      <Pricing />

      <Footer />
    </div>
  );
}
